apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "arcadedb.fullname" . }}
  labels:
    {{- include "arcadedb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arcadedb.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "arcadedb.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "arcadedb.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: arcadedb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: {{ printf "%s -Darcadedb.server.rootPassword=%s" .Values.javaOpts .Values.auth.rootPassword | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: binary
              containerPort: {{ .Values.service.binaryPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/v1/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/arcadedb/databases
            - name: config
              mountPath: /home/arcadedb/config/arcadedb-server.json
              subPath: arcadedb-server.json
      volumes:
        - name: config
          configMap:
            name: {{ include "arcadedb.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
